import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/ui/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main
          className="align-center flex min-h-screen flex-col items-center 
                  justify-between bg-white align-top"
        >
          <div className="mx-auto h-96 px-0 lg:container 2xl:w-1/5">
            <Header />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
